//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortageDataSwitch.SubmissionErrorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService", ConfigurationName="SubmissionErrorService.SubmissionErrorsServiceSoap")]
    public interface SubmissionErrorsServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService/GetSubmiss" +
            "ionError", ReplyAction="*")]
        MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponse GetSubmissionError(MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService/GetSubmiss" +
            "ionError", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponse> GetSubmissionErrorAsync(MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubmissionErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubmissionError", Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService", Order=0)]
        public MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequestBody Body;
        
        public GetSubmissionErrorRequest() {
        }
        
        public GetSubmissionErrorRequest(MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService")]
    public partial class GetSubmissionErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public GetSubmissionErrorRequestBody() {
        }
        
        public GetSubmissionErrorRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubmissionErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubmissionErrorResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService", Order=0)]
        public MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponseBody Body;
        
        public GetSubmissionErrorResponse() {
        }
        
        public GetSubmissionErrorResponse(MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmissionErrorsService")]
    public partial class GetSubmissionErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSubmissionErrorResult;
        
        public GetSubmissionErrorResponseBody() {
        }
        
        public GetSubmissionErrorResponseBody(string GetSubmissionErrorResult) {
            this.GetSubmissionErrorResult = GetSubmissionErrorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubmissionErrorsServiceSoapChannel : MortageDataSwitch.SubmissionErrorService.SubmissionErrorsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmissionErrorsServiceSoapClient : System.ServiceModel.ClientBase<MortageDataSwitch.SubmissionErrorService.SubmissionErrorsServiceSoap>, MortageDataSwitch.SubmissionErrorService.SubmissionErrorsServiceSoap {
        
        public SubmissionErrorsServiceSoapClient() {
        }
        
        public SubmissionErrorsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubmissionErrorsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubmissionErrorsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubmissionErrorsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponse MortageDataSwitch.SubmissionErrorService.SubmissionErrorsServiceSoap.GetSubmissionError(MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest request) {
            return base.Channel.GetSubmissionError(request);
        }
        
        public string GetSubmissionError(string requestXML) {
            MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest inValue = new MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest();
            inValue.Body = new MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponse retVal = ((MortageDataSwitch.SubmissionErrorService.SubmissionErrorsServiceSoap)(this)).GetSubmissionError(inValue);
            return retVal.Body.GetSubmissionErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponse> MortageDataSwitch.SubmissionErrorService.SubmissionErrorsServiceSoap.GetSubmissionErrorAsync(MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest request) {
            return base.Channel.GetSubmissionErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorResponse> GetSubmissionErrorAsync(string requestXML) {
            MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest inValue = new MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequest();
            inValue.Body = new MortageDataSwitch.SubmissionErrorService.GetSubmissionErrorRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.SubmissionErrorService.SubmissionErrorsServiceSoap)(this)).GetSubmissionErrorAsync(inValue);
        }
    }
}
