//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortageDataSwitch.LookupDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService", ConfigurationName="LookupDataService.LookupDataServiceSoap")]
    public interface LookupDataServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXml from namespace http://www.unifiedplatform/Comcorp.WebServices/LookupDataService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService/GetTableValues", ReplyAction="*")]
        MortageDataSwitch.LookupDataService.GetTableValuesResponse GetTableValues(MortageDataSwitch.LookupDataService.GetTableValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService/GetTableValues", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableValuesResponse> GetTableValuesAsync(MortageDataSwitch.LookupDataService.GetTableValuesRequest request);
        
        // CODEGEN: Generating message contract since element name requestXml from namespace http://www.unifiedplatform/Comcorp.WebServices/LookupDataService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService/GetTableValuesZi" +
            "pped", ReplyAction="*")]
        MortageDataSwitch.LookupDataService.GetTableValuesZippedResponse GetTableValuesZipped(MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService/GetTableValuesZi" +
            "pped", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableValuesZippedResponse> GetTableValuesZippedAsync(MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest request);
        
        // CODEGEN: Generating message contract since element name requestXml from namespace http://www.unifiedplatform/Comcorp.WebServices/LookupDataService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService/GetTableVersionI" +
            "nfo", ReplyAction="*")]
        MortageDataSwitch.LookupDataService.GetTableVersionInfoResponse GetTableVersionInfo(MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService/GetTableVersionI" +
            "nfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableVersionInfoResponse> GetTableVersionInfoAsync(MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableValues", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService", Order=0)]
        public MortageDataSwitch.LookupDataService.GetTableValuesRequestBody Body;
        
        public GetTableValuesRequest() {
        }
        
        public GetTableValuesRequest(MortageDataSwitch.LookupDataService.GetTableValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService")]
    public partial class GetTableValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public GetTableValuesRequestBody() {
        }
        
        public GetTableValuesRequestBody(string requestXml) {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableValuesResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService", Order=0)]
        public MortageDataSwitch.LookupDataService.GetTableValuesResponseBody Body;
        
        public GetTableValuesResponse() {
        }
        
        public GetTableValuesResponse(MortageDataSwitch.LookupDataService.GetTableValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService")]
    public partial class GetTableValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTableValuesResult;
        
        public GetTableValuesResponseBody() {
        }
        
        public GetTableValuesResponseBody(string GetTableValuesResult) {
            this.GetTableValuesResult = GetTableValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableValuesZippedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableValuesZipped", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService", Order=0)]
        public MortageDataSwitch.LookupDataService.GetTableValuesZippedRequestBody Body;
        
        public GetTableValuesZippedRequest() {
        }
        
        public GetTableValuesZippedRequest(MortageDataSwitch.LookupDataService.GetTableValuesZippedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService")]
    public partial class GetTableValuesZippedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public GetTableValuesZippedRequestBody() {
        }
        
        public GetTableValuesZippedRequestBody(string requestXml) {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableValuesZippedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableValuesZippedResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService", Order=0)]
        public MortageDataSwitch.LookupDataService.GetTableValuesZippedResponseBody Body;
        
        public GetTableValuesZippedResponse() {
        }
        
        public GetTableValuesZippedResponse(MortageDataSwitch.LookupDataService.GetTableValuesZippedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService")]
    public partial class GetTableValuesZippedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTableValuesZippedResult;
        
        public GetTableValuesZippedResponseBody() {
        }
        
        public GetTableValuesZippedResponseBody(string GetTableValuesZippedResult) {
            this.GetTableValuesZippedResult = GetTableValuesZippedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableVersionInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableVersionInfo", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService", Order=0)]
        public MortageDataSwitch.LookupDataService.GetTableVersionInfoRequestBody Body;
        
        public GetTableVersionInfoRequest() {
        }
        
        public GetTableVersionInfoRequest(MortageDataSwitch.LookupDataService.GetTableVersionInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService")]
    public partial class GetTableVersionInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXml;
        
        public GetTableVersionInfoRequestBody() {
        }
        
        public GetTableVersionInfoRequestBody(string requestXml) {
            this.requestXml = requestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableVersionInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableVersionInfoResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService", Order=0)]
        public MortageDataSwitch.LookupDataService.GetTableVersionInfoResponseBody Body;
        
        public GetTableVersionInfoResponse() {
        }
        
        public GetTableVersionInfoResponse(MortageDataSwitch.LookupDataService.GetTableVersionInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LookupDataService")]
    public partial class GetTableVersionInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTableVersionInfoResult;
        
        public GetTableVersionInfoResponseBody() {
        }
        
        public GetTableVersionInfoResponseBody(string GetTableVersionInfoResult) {
            this.GetTableVersionInfoResult = GetTableVersionInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LookupDataServiceSoapChannel : MortageDataSwitch.LookupDataService.LookupDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookupDataServiceSoapClient : System.ServiceModel.ClientBase<MortageDataSwitch.LookupDataService.LookupDataServiceSoap>, MortageDataSwitch.LookupDataService.LookupDataServiceSoap {
        
        public LookupDataServiceSoapClient() {
        }
        
        public LookupDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LookupDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.LookupDataService.GetTableValuesResponse MortageDataSwitch.LookupDataService.LookupDataServiceSoap.GetTableValues(MortageDataSwitch.LookupDataService.GetTableValuesRequest request) {
            return base.Channel.GetTableValues(request);
        }
        
        public string GetTableValues(string requestXml) {
            MortageDataSwitch.LookupDataService.GetTableValuesRequest inValue = new MortageDataSwitch.LookupDataService.GetTableValuesRequest();
            inValue.Body = new MortageDataSwitch.LookupDataService.GetTableValuesRequestBody();
            inValue.Body.requestXml = requestXml;
            MortageDataSwitch.LookupDataService.GetTableValuesResponse retVal = ((MortageDataSwitch.LookupDataService.LookupDataServiceSoap)(this)).GetTableValues(inValue);
            return retVal.Body.GetTableValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableValuesResponse> MortageDataSwitch.LookupDataService.LookupDataServiceSoap.GetTableValuesAsync(MortageDataSwitch.LookupDataService.GetTableValuesRequest request) {
            return base.Channel.GetTableValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableValuesResponse> GetTableValuesAsync(string requestXml) {
            MortageDataSwitch.LookupDataService.GetTableValuesRequest inValue = new MortageDataSwitch.LookupDataService.GetTableValuesRequest();
            inValue.Body = new MortageDataSwitch.LookupDataService.GetTableValuesRequestBody();
            inValue.Body.requestXml = requestXml;
            return ((MortageDataSwitch.LookupDataService.LookupDataServiceSoap)(this)).GetTableValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.LookupDataService.GetTableValuesZippedResponse MortageDataSwitch.LookupDataService.LookupDataServiceSoap.GetTableValuesZipped(MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest request) {
            return base.Channel.GetTableValuesZipped(request);
        }
        
        public string GetTableValuesZipped(string requestXml) {
            MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest inValue = new MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest();
            inValue.Body = new MortageDataSwitch.LookupDataService.GetTableValuesZippedRequestBody();
            inValue.Body.requestXml = requestXml;
            MortageDataSwitch.LookupDataService.GetTableValuesZippedResponse retVal = ((MortageDataSwitch.LookupDataService.LookupDataServiceSoap)(this)).GetTableValuesZipped(inValue);
            return retVal.Body.GetTableValuesZippedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableValuesZippedResponse> MortageDataSwitch.LookupDataService.LookupDataServiceSoap.GetTableValuesZippedAsync(MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest request) {
            return base.Channel.GetTableValuesZippedAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableValuesZippedResponse> GetTableValuesZippedAsync(string requestXml) {
            MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest inValue = new MortageDataSwitch.LookupDataService.GetTableValuesZippedRequest();
            inValue.Body = new MortageDataSwitch.LookupDataService.GetTableValuesZippedRequestBody();
            inValue.Body.requestXml = requestXml;
            return ((MortageDataSwitch.LookupDataService.LookupDataServiceSoap)(this)).GetTableValuesZippedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.LookupDataService.GetTableVersionInfoResponse MortageDataSwitch.LookupDataService.LookupDataServiceSoap.GetTableVersionInfo(MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest request) {
            return base.Channel.GetTableVersionInfo(request);
        }
        
        public string GetTableVersionInfo(string requestXml) {
            MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest inValue = new MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest();
            inValue.Body = new MortageDataSwitch.LookupDataService.GetTableVersionInfoRequestBody();
            inValue.Body.requestXml = requestXml;
            MortageDataSwitch.LookupDataService.GetTableVersionInfoResponse retVal = ((MortageDataSwitch.LookupDataService.LookupDataServiceSoap)(this)).GetTableVersionInfo(inValue);
            return retVal.Body.GetTableVersionInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableVersionInfoResponse> MortageDataSwitch.LookupDataService.LookupDataServiceSoap.GetTableVersionInfoAsync(MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest request) {
            return base.Channel.GetTableVersionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.LookupDataService.GetTableVersionInfoResponse> GetTableVersionInfoAsync(string requestXml) {
            MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest inValue = new MortageDataSwitch.LookupDataService.GetTableVersionInfoRequest();
            inValue.Body = new MortageDataSwitch.LookupDataService.GetTableVersionInfoRequestBody();
            inValue.Body.requestXml = requestXml;
            return ((MortageDataSwitch.LookupDataService.LookupDataServiceSoap)(this)).GetTableVersionInfoAsync(inValue);
        }
    }
}
