//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortageDataSwitch.FeedbackService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService", ConfigurationName="FeedbackService.FeedbackServiceSoap")]
    public interface FeedbackServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/FeedbackService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService/SendRequest", ReplyAction="*")]
        MortageDataSwitch.FeedbackService.SendRequestResponse SendRequest(MortageDataSwitch.FeedbackService.SendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService/SendRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.FeedbackService.SendRequestResponse> SendRequestAsync(MortageDataSwitch.FeedbackService.SendRequestRequest request);
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/FeedbackService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService/ReceiveReply", ReplyAction="*")]
        MortageDataSwitch.FeedbackService.ReceiveReplyResponse ReceiveReply(MortageDataSwitch.FeedbackService.ReceiveReplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService/ReceiveReply", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.FeedbackService.ReceiveReplyResponse> ReceiveReplyAsync(MortageDataSwitch.FeedbackService.ReceiveReplyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequest", Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService", Order=0)]
        public MortageDataSwitch.FeedbackService.SendRequestRequestBody Body;
        
        public SendRequestRequest() {
        }
        
        public SendRequestRequest(MortageDataSwitch.FeedbackService.SendRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService")]
    public partial class SendRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public SendRequestRequestBody() {
        }
        
        public SendRequestRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequestResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService", Order=0)]
        public MortageDataSwitch.FeedbackService.SendRequestResponseBody Body;
        
        public SendRequestResponse() {
        }
        
        public SendRequestResponse(MortageDataSwitch.FeedbackService.SendRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService")]
    public partial class SendRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendRequestResult;
        
        public SendRequestResponseBody() {
        }
        
        public SendRequestResponseBody(string SendRequestResult) {
            this.SendRequestResult = SendRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReply", Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService", Order=0)]
        public MortageDataSwitch.FeedbackService.ReceiveReplyRequestBody Body;
        
        public ReceiveReplyRequest() {
        }
        
        public ReceiveReplyRequest(MortageDataSwitch.FeedbackService.ReceiveReplyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService")]
    public partial class ReceiveReplyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public ReceiveReplyRequestBody() {
        }
        
        public ReceiveReplyRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReplyResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService", Order=0)]
        public MortageDataSwitch.FeedbackService.ReceiveReplyResponseBody Body;
        
        public ReceiveReplyResponse() {
        }
        
        public ReceiveReplyResponse(MortageDataSwitch.FeedbackService.ReceiveReplyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/FeedbackService")]
    public partial class ReceiveReplyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReceiveReplyResult;
        
        public ReceiveReplyResponseBody() {
        }
        
        public ReceiveReplyResponseBody(string ReceiveReplyResult) {
            this.ReceiveReplyResult = ReceiveReplyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FeedbackServiceSoapChannel : MortageDataSwitch.FeedbackService.FeedbackServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedbackServiceSoapClient : System.ServiceModel.ClientBase<MortageDataSwitch.FeedbackService.FeedbackServiceSoap>, MortageDataSwitch.FeedbackService.FeedbackServiceSoap {
        
        public FeedbackServiceSoapClient() {
        }
        
        public FeedbackServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedbackServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedbackServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedbackServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.FeedbackService.SendRequestResponse MortageDataSwitch.FeedbackService.FeedbackServiceSoap.SendRequest(MortageDataSwitch.FeedbackService.SendRequestRequest request) {
            return base.Channel.SendRequest(request);
        }
        
        public string SendRequest(string requestXML) {
            MortageDataSwitch.FeedbackService.SendRequestRequest inValue = new MortageDataSwitch.FeedbackService.SendRequestRequest();
            inValue.Body = new MortageDataSwitch.FeedbackService.SendRequestRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.FeedbackService.SendRequestResponse retVal = ((MortageDataSwitch.FeedbackService.FeedbackServiceSoap)(this)).SendRequest(inValue);
            return retVal.Body.SendRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.FeedbackService.SendRequestResponse> MortageDataSwitch.FeedbackService.FeedbackServiceSoap.SendRequestAsync(MortageDataSwitch.FeedbackService.SendRequestRequest request) {
            return base.Channel.SendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.FeedbackService.SendRequestResponse> SendRequestAsync(string requestXML) {
            MortageDataSwitch.FeedbackService.SendRequestRequest inValue = new MortageDataSwitch.FeedbackService.SendRequestRequest();
            inValue.Body = new MortageDataSwitch.FeedbackService.SendRequestRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.FeedbackService.FeedbackServiceSoap)(this)).SendRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.FeedbackService.ReceiveReplyResponse MortageDataSwitch.FeedbackService.FeedbackServiceSoap.ReceiveReply(MortageDataSwitch.FeedbackService.ReceiveReplyRequest request) {
            return base.Channel.ReceiveReply(request);
        }
        
        public string ReceiveReply(string requestXML) {
            MortageDataSwitch.FeedbackService.ReceiveReplyRequest inValue = new MortageDataSwitch.FeedbackService.ReceiveReplyRequest();
            inValue.Body = new MortageDataSwitch.FeedbackService.ReceiveReplyRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.FeedbackService.ReceiveReplyResponse retVal = ((MortageDataSwitch.FeedbackService.FeedbackServiceSoap)(this)).ReceiveReply(inValue);
            return retVal.Body.ReceiveReplyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.FeedbackService.ReceiveReplyResponse> MortageDataSwitch.FeedbackService.FeedbackServiceSoap.ReceiveReplyAsync(MortageDataSwitch.FeedbackService.ReceiveReplyRequest request) {
            return base.Channel.ReceiveReplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.FeedbackService.ReceiveReplyResponse> ReceiveReplyAsync(string requestXML) {
            MortageDataSwitch.FeedbackService.ReceiveReplyRequest inValue = new MortageDataSwitch.FeedbackService.ReceiveReplyRequest();
            inValue.Body = new MortageDataSwitch.FeedbackService.ReceiveReplyRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.FeedbackService.FeedbackServiceSoap)(this)).ReceiveReplyAsync(inValue);
        }
    }
}
