//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortageDataSwitch.ValidationErrorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService", ConfigurationName="ValidationErrorService.ValidationErrorsServiceSoap")]
    public interface ValidationErrorsServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService/GetValidat" +
            "ionError", ReplyAction="*")]
        MortageDataSwitch.ValidationErrorService.GetValidationErrorResponse GetValidationError(MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService/GetValidat" +
            "ionError", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.ValidationErrorService.GetValidationErrorResponse> GetValidationErrorAsync(MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidationErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidationError", Namespace="http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService", Order=0)]
        public MortageDataSwitch.ValidationErrorService.GetValidationErrorRequestBody Body;
        
        public GetValidationErrorRequest() {
        }
        
        public GetValidationErrorRequest(MortageDataSwitch.ValidationErrorService.GetValidationErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService")]
    public partial class GetValidationErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public GetValidationErrorRequestBody() {
        }
        
        public GetValidationErrorRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidationErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidationErrorResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService", Order=0)]
        public MortageDataSwitch.ValidationErrorService.GetValidationErrorResponseBody Body;
        
        public GetValidationErrorResponse() {
        }
        
        public GetValidationErrorResponse(MortageDataSwitch.ValidationErrorService.GetValidationErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/ValidationErrorsService")]
    public partial class GetValidationErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetValidationErrorResult;
        
        public GetValidationErrorResponseBody() {
        }
        
        public GetValidationErrorResponseBody(string GetValidationErrorResult) {
            this.GetValidationErrorResult = GetValidationErrorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidationErrorsServiceSoapChannel : MortageDataSwitch.ValidationErrorService.ValidationErrorsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidationErrorsServiceSoapClient : System.ServiceModel.ClientBase<MortageDataSwitch.ValidationErrorService.ValidationErrorsServiceSoap>, MortageDataSwitch.ValidationErrorService.ValidationErrorsServiceSoap {
        
        public ValidationErrorsServiceSoapClient() {
        }
        
        public ValidationErrorsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidationErrorsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationErrorsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationErrorsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.ValidationErrorService.GetValidationErrorResponse MortageDataSwitch.ValidationErrorService.ValidationErrorsServiceSoap.GetValidationError(MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest request) {
            return base.Channel.GetValidationError(request);
        }
        
        public string GetValidationError(string requestXML) {
            MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest inValue = new MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest();
            inValue.Body = new MortageDataSwitch.ValidationErrorService.GetValidationErrorRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.ValidationErrorService.GetValidationErrorResponse retVal = ((MortageDataSwitch.ValidationErrorService.ValidationErrorsServiceSoap)(this)).GetValidationError(inValue);
            return retVal.Body.GetValidationErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.ValidationErrorService.GetValidationErrorResponse> MortageDataSwitch.ValidationErrorService.ValidationErrorsServiceSoap.GetValidationErrorAsync(MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest request) {
            return base.Channel.GetValidationErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.ValidationErrorService.GetValidationErrorResponse> GetValidationErrorAsync(string requestXML) {
            MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest inValue = new MortageDataSwitch.ValidationErrorService.GetValidationErrorRequest();
            inValue.Body = new MortageDataSwitch.ValidationErrorService.GetValidationErrorRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.ValidationErrorService.ValidationErrorsServiceSoap)(this)).GetValidationErrorAsync(inValue);
        }
    }
}
