//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortageDataSwitch.TemplateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/TemplateServices", ConfigurationName="TemplateService.TemplateServiceSoap")]
    public interface TemplateServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/TemplateServices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/TemplateServices/GetTemplates", ReplyAction="*")]
        MortageDataSwitch.TemplateService.GetTemplatesResponse GetTemplates(MortageDataSwitch.TemplateService.GetTemplatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/TemplateServices/GetTemplates", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.TemplateService.GetTemplatesResponse> GetTemplatesAsync(MortageDataSwitch.TemplateService.GetTemplatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplates", Namespace="http://www.unifiedplatform/Comcorp.WebServices/TemplateServices", Order=0)]
        public MortageDataSwitch.TemplateService.GetTemplatesRequestBody Body;
        
        public GetTemplatesRequest() {
        }
        
        public GetTemplatesRequest(MortageDataSwitch.TemplateService.GetTemplatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/TemplateServices")]
    public partial class GetTemplatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public GetTemplatesRequestBody() {
        }
        
        public GetTemplatesRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplatesResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/TemplateServices", Order=0)]
        public MortageDataSwitch.TemplateService.GetTemplatesResponseBody Body;
        
        public GetTemplatesResponse() {
        }
        
        public GetTemplatesResponse(MortageDataSwitch.TemplateService.GetTemplatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/TemplateServices")]
    public partial class GetTemplatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTemplatesResult;
        
        public GetTemplatesResponseBody() {
        }
        
        public GetTemplatesResponseBody(string GetTemplatesResult) {
            this.GetTemplatesResult = GetTemplatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TemplateServiceSoapChannel : MortageDataSwitch.TemplateService.TemplateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemplateServiceSoapClient : System.ServiceModel.ClientBase<MortageDataSwitch.TemplateService.TemplateServiceSoap>, MortageDataSwitch.TemplateService.TemplateServiceSoap {
        
        public TemplateServiceSoapClient() {
        }
        
        public TemplateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemplateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.TemplateService.GetTemplatesResponse MortageDataSwitch.TemplateService.TemplateServiceSoap.GetTemplates(MortageDataSwitch.TemplateService.GetTemplatesRequest request) {
            return base.Channel.GetTemplates(request);
        }
        
        public string GetTemplates(string requestXML) {
            MortageDataSwitch.TemplateService.GetTemplatesRequest inValue = new MortageDataSwitch.TemplateService.GetTemplatesRequest();
            inValue.Body = new MortageDataSwitch.TemplateService.GetTemplatesRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.TemplateService.GetTemplatesResponse retVal = ((MortageDataSwitch.TemplateService.TemplateServiceSoap)(this)).GetTemplates(inValue);
            return retVal.Body.GetTemplatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.TemplateService.GetTemplatesResponse> MortageDataSwitch.TemplateService.TemplateServiceSoap.GetTemplatesAsync(MortageDataSwitch.TemplateService.GetTemplatesRequest request) {
            return base.Channel.GetTemplatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.TemplateService.GetTemplatesResponse> GetTemplatesAsync(string requestXML) {
            MortageDataSwitch.TemplateService.GetTemplatesRequest inValue = new MortageDataSwitch.TemplateService.GetTemplatesRequest();
            inValue.Body = new MortageDataSwitch.TemplateService.GetTemplatesRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.TemplateService.TemplateServiceSoap)(this)).GetTemplatesAsync(inValue);
        }
    }
}
