//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortageDataSwitch.LiveRepliesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService", ConfigurationName="LiveRepliesService.LiveRepliesServiceSoap")]
    public interface LiveRepliesServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService/GetLiveRepliesByA" +
            "ppRef", ReplyAction="*")]
        MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponse GetLiveRepliesByAppRef(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService/GetLiveRepliesByA" +
            "ppRef", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponse> GetLiveRepliesByAppRefAsync(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest request);
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService/GetLiveRepliesByD" +
            "ateRange", ReplyAction="*")]
        MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponse GetLiveRepliesByDateRange(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService/GetLiveRepliesByD" +
            "ateRange", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponse> GetLiveRepliesByDateRangeAsync(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveRepliesByAppRefRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveRepliesByAppRef", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService", Order=0)]
        public MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequestBody Body;
        
        public GetLiveRepliesByAppRefRequest() {
        }
        
        public GetLiveRepliesByAppRefRequest(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService")]
    public partial class GetLiveRepliesByAppRefRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public GetLiveRepliesByAppRefRequestBody() {
        }
        
        public GetLiveRepliesByAppRefRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveRepliesByAppRefResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveRepliesByAppRefResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService", Order=0)]
        public MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponseBody Body;
        
        public GetLiveRepliesByAppRefResponse() {
        }
        
        public GetLiveRepliesByAppRefResponse(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService")]
    public partial class GetLiveRepliesByAppRefResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLiveRepliesByAppRefResult;
        
        public GetLiveRepliesByAppRefResponseBody() {
        }
        
        public GetLiveRepliesByAppRefResponseBody(string GetLiveRepliesByAppRefResult) {
            this.GetLiveRepliesByAppRefResult = GetLiveRepliesByAppRefResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveRepliesByDateRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveRepliesByDateRange", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService", Order=0)]
        public MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequestBody Body;
        
        public GetLiveRepliesByDateRangeRequest() {
        }
        
        public GetLiveRepliesByDateRangeRequest(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService")]
    public partial class GetLiveRepliesByDateRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public GetLiveRepliesByDateRangeRequestBody() {
        }
        
        public GetLiveRepliesByDateRangeRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveRepliesByDateRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveRepliesByDateRangeResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService", Order=0)]
        public MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponseBody Body;
        
        public GetLiveRepliesByDateRangeResponse() {
        }
        
        public GetLiveRepliesByDateRangeResponse(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/LiveReplyService")]
    public partial class GetLiveRepliesByDateRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLiveRepliesByDateRangeResult;
        
        public GetLiveRepliesByDateRangeResponseBody() {
        }
        
        public GetLiveRepliesByDateRangeResponseBody(string GetLiveRepliesByDateRangeResult) {
            this.GetLiveRepliesByDateRangeResult = GetLiveRepliesByDateRangeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LiveRepliesServiceSoapChannel : MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiveRepliesServiceSoapClient : System.ServiceModel.ClientBase<MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap>, MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap {
        
        public LiveRepliesServiceSoapClient() {
        }
        
        public LiveRepliesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveRepliesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveRepliesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveRepliesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponse MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap.GetLiveRepliesByAppRef(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest request) {
            return base.Channel.GetLiveRepliesByAppRef(request);
        }
        
        public string GetLiveRepliesByAppRef(string requestXML) {
            MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest inValue = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest();
            inValue.Body = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponse retVal = ((MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap)(this)).GetLiveRepliesByAppRef(inValue);
            return retVal.Body.GetLiveRepliesByAppRefResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponse> MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap.GetLiveRepliesByAppRefAsync(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest request) {
            return base.Channel.GetLiveRepliesByAppRefAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefResponse> GetLiveRepliesByAppRefAsync(string requestXML) {
            MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest inValue = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequest();
            inValue.Body = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByAppRefRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap)(this)).GetLiveRepliesByAppRefAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponse MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap.GetLiveRepliesByDateRange(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest request) {
            return base.Channel.GetLiveRepliesByDateRange(request);
        }
        
        public string GetLiveRepliesByDateRange(string requestXML) {
            MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest inValue = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest();
            inValue.Body = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponse retVal = ((MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap)(this)).GetLiveRepliesByDateRange(inValue);
            return retVal.Body.GetLiveRepliesByDateRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponse> MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap.GetLiveRepliesByDateRangeAsync(MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest request) {
            return base.Channel.GetLiveRepliesByDateRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeResponse> GetLiveRepliesByDateRangeAsync(string requestXML) {
            MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest inValue = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequest();
            inValue.Body = new MortageDataSwitch.LiveRepliesService.GetLiveRepliesByDateRangeRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.LiveRepliesService.LiveRepliesServiceSoap)(this)).GetLiveRepliesByDateRangeAsync(inValue);
        }
    }
}
