//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortageDataSwitch.SubmitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmitService", ConfigurationName="SubmitService.SubmitServiceSoap")]
    public interface SubmitServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestXML from namespace http://www.unifiedplatform/Comcorp.WebServices/SubmitService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/SubmitService/SubmitApplication", ReplyAction="*")]
        MortageDataSwitch.SubmitService.SubmitApplicationResponse SubmitApplication(MortageDataSwitch.SubmitService.SubmitApplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.unifiedplatform/Comcorp.WebServices/SubmitService/SubmitApplication", ReplyAction="*")]
        System.Threading.Tasks.Task<MortageDataSwitch.SubmitService.SubmitApplicationResponse> SubmitApplicationAsync(MortageDataSwitch.SubmitService.SubmitApplicationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitApplication", Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmitService", Order=0)]
        public MortageDataSwitch.SubmitService.SubmitApplicationRequestBody Body;
        
        public SubmitApplicationRequest() {
        }
        
        public SubmitApplicationRequest(MortageDataSwitch.SubmitService.SubmitApplicationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmitService")]
    public partial class SubmitApplicationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public SubmitApplicationRequestBody() {
        }
        
        public SubmitApplicationRequestBody(string requestXML) {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitApplicationResponse", Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmitService", Order=0)]
        public MortageDataSwitch.SubmitService.SubmitApplicationResponseBody Body;
        
        public SubmitApplicationResponse() {
        }
        
        public SubmitApplicationResponse(MortageDataSwitch.SubmitService.SubmitApplicationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.unifiedplatform/Comcorp.WebServices/SubmitService")]
    public partial class SubmitApplicationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitApplicationResult;
        
        public SubmitApplicationResponseBody() {
        }
        
        public SubmitApplicationResponseBody(string SubmitApplicationResult) {
            this.SubmitApplicationResult = SubmitApplicationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubmitServiceSoapChannel : MortageDataSwitch.SubmitService.SubmitServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmitServiceSoapClient : System.ServiceModel.ClientBase<MortageDataSwitch.SubmitService.SubmitServiceSoap>, MortageDataSwitch.SubmitService.SubmitServiceSoap {
        
        public SubmitServiceSoapClient() {
        }
        
        public SubmitServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubmitServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubmitServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubmitServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MortageDataSwitch.SubmitService.SubmitApplicationResponse MortageDataSwitch.SubmitService.SubmitServiceSoap.SubmitApplication(MortageDataSwitch.SubmitService.SubmitApplicationRequest request) {
            return base.Channel.SubmitApplication(request);
        }
        
        public string SubmitApplication(string requestXML) {
            MortageDataSwitch.SubmitService.SubmitApplicationRequest inValue = new MortageDataSwitch.SubmitService.SubmitApplicationRequest();
            inValue.Body = new MortageDataSwitch.SubmitService.SubmitApplicationRequestBody();
            inValue.Body.requestXML = requestXML;
            MortageDataSwitch.SubmitService.SubmitApplicationResponse retVal = ((MortageDataSwitch.SubmitService.SubmitServiceSoap)(this)).SubmitApplication(inValue);
            return retVal.Body.SubmitApplicationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MortageDataSwitch.SubmitService.SubmitApplicationResponse> MortageDataSwitch.SubmitService.SubmitServiceSoap.SubmitApplicationAsync(MortageDataSwitch.SubmitService.SubmitApplicationRequest request) {
            return base.Channel.SubmitApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MortageDataSwitch.SubmitService.SubmitApplicationResponse> SubmitApplicationAsync(string requestXML) {
            MortageDataSwitch.SubmitService.SubmitApplicationRequest inValue = new MortageDataSwitch.SubmitService.SubmitApplicationRequest();
            inValue.Body = new MortageDataSwitch.SubmitService.SubmitApplicationRequestBody();
            inValue.Body.requestXML = requestXML;
            return ((MortageDataSwitch.SubmitService.SubmitServiceSoap)(this)).SubmitApplicationAsync(inValue);
        }
    }
}
